### ISSUE TITLE
Add ScreenBrightnessMonitor

### ISSUE THREAD

**Issue by Descartess** [eBardX/XestiMonitors#17] opened 2018-03-21 13:45 UTC
#### Feature Name 

- ScreenBrightnessMonitor
#### Events

-  `UIScreenBrightnessDidChange`
#### Platform

- iOS/tvOS

**Comment by eBardX** [comment] 2018-03-21 18:57
Duplicate of #15

**Closed** 2018-03-21 18:57 UTC
Labels: feature request
